SELECT NAME 
FROM EMPLOYEE E  JOIN (SELECT DEPARTMENT_ID, MAX(SALARY) AS SalaryMax 
                       FROM EMPLOYEE EMP 
                       GROUP BY DEPARTMENT_ID) D
ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
where E.SALARY = D.SalaryMax
